### ISSUE TITLE
HRULE dashes are not supported

### ISSUE THREAD

**Issue by smkent** [manuelluis/jsrrdgraph#22]
[From the rrdtool page](http://oss.oetiker.ch/rrdtool/doc/rrdgraph_graph.en.html):

> `HRULE:value#color[:legend][:dashes[=on_s[,off_s[,on_s,off_s]...]][:dash-offset=offset]]`

> Draw a horizontal line at value. HRULE acts much like LINE except that will have no effect on the scale of the graph. If a HRULE is outside the graphing area it will just not be visible.

Example HRULE:

    HRULE:4#ecd748::dashes

rrdgraph example with dashed HRULEs:

![rrdgraph_1](https://cloud.githubusercontent.com/assets/2831985/6540698/69a921c4-c461-11e4-991b-e7d71fb758be.png)

jsrrdgraph renders the HRULEs as solid lines:

![2](https://cloud.githubusercontent.com/assets/2831985/6540704/aa14684a-c461-11e4-82f1-bf0da8ea8109.png)

**Comment by manuelluis** [comment]
Added dashes in LINE, HRULE and VRULE.
